/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include <stdio.h>
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
I2C_HandleTypeDef hi2c1;

SPI_HandleTypeDef hspi1;

UART_HandleTypeDef huart1;

/* USER CODE BEGIN PV */

// Macros for driving the nRF24 control pins
#define NRF24_CE_HIGH()  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PIN_SET)
#define NRF24_CE_LOW()   HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PIN_RESET)
#define NRF24_CSN_HIGH() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_1, GPIO_PIN_SET)
#define NRF24_CSN_LOW()  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_1, GPIO_PIN_RESET)

// Custom data frame structure supporting full telemetry (12 bytes total)
typedef struct __attribute__((packed)) {
    uint32_t sample_id;
    float temperature;
    float humidity;
} SensorPayload;

SensorPayload my_data;
uint32_t loop_counter = 0;

// Hardware handle generated by CubeMX for our I2C setup
extern I2C_HandleTypeDef hi2c1;
#define AHT_I2C_ADDR (0x38 << 1) // 7-bit standard address 0x38 shifted for HAL write formatting

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_SPI1_Init(void);
static void MX_USART1_UART_Init(void);
static void MX_I2C1_Init(void);
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

// 1. Intercept printf and push characters out of USART1 hardware
#ifdef __GNUC__
#define PUTCHAR_PROTOTYPE int __io_putchar(int ch)
#else
#define PUTCHAR_PROTOTYPE int fputc(int ch, FILE *f)
#endif

PUTCHAR_PROTOTYPE
{
  HAL_UART_Transmit(&huart1, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
  return ch;
}

void AHT_Init(void) {
    uint8_t init_cmd[] = {0xBE, 0x08, 0x00};
    HAL_Delay(40); // Wait for sensor startup power stabilization
    HAL_I2C_Master_Transmit(&hi2c1, AHT_I2C_ADDR, init_cmd, 3, HAL_MAX_DELAY);
    HAL_Delay(20);
}

// Interrogates the sensor, extracts data registers, and computes actual float values
void AHT_Read(float *temperature, float *humidity) {
    uint8_t read_cmd[] = {0xAC, 0x33, 0x00};
    uint8_t raw_buffer[6];

    // Trigger measurement matrix cycle
    HAL_I2C_Master_Transmit(&hi2c1, AHT_I2C_ADDR, read_cmd, 3, HAL_MAX_DELAY);
    HAL_Delay(80); // Wait for conversion process to finalize (75ms minimum requirement)

    // Extract 6 data status bytes
    if (HAL_I2C_Master_Receive(&hi2c1, AHT_I2C_ADDR, raw_buffer, 6, HAL_MAX_DELAY) == HAL_OK) {
        // Parse 20-bit raw data chunks out of individual register registers
        uint32_t raw_humidity = (((uint32_t)raw_buffer[1] << 12) | ((uint32_t)raw_buffer[2] << 4) | ((uint32_t)raw_buffer[3] >> 4)) & 0xFFFFF;
        uint32_t raw_temperature = (((uint32_t)(raw_buffer[3] & 0x0F) << 16) | ((uint32_t)raw_buffer[4] << 8) | (uint32_t)raw_buffer[5]) & 0xFFFFF;

        // Physical value metric scaling conversions
        *humidity = ((float)raw_humidity / 1048576.0f) * 100.0f;
        *temperature = ((float)raw_temperature / 1048576.0f) * 200.0f - 50.0f;
    }
}

// 2. Low-level routine to write data to an nRF24 register address
void NRF24_WriteRegister(uint8_t reg, uint8_t value) {
    uint8_t buf[2];
    // Clear upper bits and cleanly add the Write Command mask (0x20)
    buf[0] = (reg & 0x1F) | 0x20;
    buf[1] = value;

    NRF24_CSN_LOW();
    HAL_SPI_Transmit(&hspi1, buf, 2, HAL_MAX_DELAY);
    NRF24_CSN_HIGH();
}

void NRF24_WriteRegisterBuf(uint8_t reg, uint8_t *buf, uint8_t len) {
    uint8_t cmd = (reg & 0x1F) | 0x20;
    NRF24_CSN_LOW();
    HAL_SPI_Transmit(&hspi1, &cmd, 1, HAL_MAX_DELAY);
    HAL_SPI_Transmit(&hspi1, buf, len, HAL_MAX_DELAY);
    NRF24_CSN_HIGH();
}

void NRF24_FlushTX(void) {
    uint8_t cmd = 0xE1; // FLUSH_TX command
    NRF24_CSN_LOW();
    HAL_SPI_Transmit(&hspi1, &cmd, 1, HAL_MAX_DELAY);
    NRF24_CSN_HIGH();
}

uint8_t NRF24_ReadRegister(uint8_t reg) {
    uint8_t cmd = reg & 0x1F; // Read command mask
    uint8_t val = 0;

    NRF24_CSN_LOW();
    HAL_SPI_Transmit(&hspi1, &cmd, 1, HAL_MAX_DELAY);
    HAL_SPI_Receive(&hspi1, &val, 1, HAL_MAX_DELAY);
    NRF24_CSN_HIGH();

    return val;
}

// 3. Basic radio configuration sequence for a simple broadcast pipeline
void NRF24_Init(void) {
    NRF24_CE_LOW();
    NRF24_CSN_HIGH();
    HAL_Delay(50);

    NRF24_WriteRegister(0x00, 0x0E); // CONFIG: Power up, 2-byte CRC, Transmitter mode
    NRF24_WriteRegister(0x01, 0x00); // EN_AA: Explicitly disable Auto-ACK on all pipes
    NRF24_WriteRegister(0x05, 0x4C); // RF_CH: Channel 76 (2.476 GHz)
    NRF24_WriteRegister(0x06, 0x00); // RF_SETUP: 1 Mbps data rate, 0 dBm output

    // Use a unique, custom 5-byte address instead of the factory default
    uint8_t address[5] = {0x12, 0x34, 0x56, 0x78, 0x9A};
    NRF24_WriteRegisterBuf(0x10, address, 5); // TX_ADDR
}

// 4. Transmits a raw structured block of memory across the airwaves
void NRF24_TransmitPacket(uint8_t *payload, uint8_t size) {
    uint8_t cmd = 0xA0; // Write TX payload

    // 1. Clear status flags (Max RT, TX_DS, RX_DR) by writing 1s to them
    NRF24_WriteRegister(0x07, 0x70);

    // 2. Force flush the transmission memory so old failed packets don't block us
    uint8_t flush_cmd = 0xE1; // FLUSH_TX command
    NRF24_CSN_LOW();
    HAL_SPI_Transmit(&hspi1, &flush_cmd, 1, HAL_MAX_DELAY);
    NRF24_CSN_HIGH();

    // 3. Load the new payload
    NRF24_CSN_LOW();
    HAL_SPI_Transmit(&hspi1, &cmd, 1, HAL_MAX_DELAY);
    HAL_SPI_Transmit(&hspi1, payload, size, HAL_MAX_DELAY);
    NRF24_CSN_HIGH();

    // 4. Pulse CE pin to transmit
    NRF24_CE_HIGH();
    HAL_Delay(1);
    NRF24_CE_LOW();
}

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{

  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_SPI1_Init();
  MX_USART1_UART_Init();
  MX_I2C1_Init();
  /* USER CODE BEGIN 2 */

  NRF24_Init();
  AHT_Init(); // Fire up I2C calibrations
  uint8_t channel = NRF24_ReadRegister(0x05);
  printf("nRF24 SPI Test - Channel Register reads: 0x%02X (Expected: 0x4C)\r\n", channel);

  printf("--- System Online: Broadcasting Telemetry ---\r\n");

  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
    {
          float live_temp = 0.0f;
          float live_hum = 0.0f;

          // 1. Fetch real physical data points from our I2C wires
          AHT_Read(&live_temp, &live_hum);

          // 2. Wrap those metrics into our structural data pipeline framework
          my_data.sample_id = ++loop_counter;
          my_data.temperature = live_temp;
          my_data.humidity = live_hum;

          // 3. Status Print to USART1 local debugging console
          printf("[STM32 Node] ID: %lu | Temp: %.2f C | Hum: %.2f %%\r\n",
                 my_data.sample_id, my_data.temperature, my_data.humidity);

          // 4. Send the updated 12-byte packed framework out across the airwaves
          NRF24_TransmitPacket((uint8_t*)&my_data, sizeof(my_data));

          // Success Double-Blink routine indicators
          HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET);
          HAL_Delay(80);
          HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET);
          HAL_Delay(80);
          HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET);
          HAL_Delay(80);
          HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET);

          HAL_Delay(760);



    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.HSEPredivValue = RCC_HSE_PREDIV_DIV1;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL9;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief I2C1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_I2C1_Init(void)
{

  /* USER CODE BEGIN I2C1_Init 0 */

  /* USER CODE END I2C1_Init 0 */

  /* USER CODE BEGIN I2C1_Init 1 */

  /* USER CODE END I2C1_Init 1 */
  hi2c1.Instance = I2C1;
  hi2c1.Init.ClockSpeed = 100000;
  hi2c1.Init.DutyCycle = I2C_DUTYCYCLE_2;
  hi2c1.Init.OwnAddress1 = 0;
  hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
  hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
  hi2c1.Init.OwnAddress2 = 0;
  hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
  hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
  if (HAL_I2C_Init(&hi2c1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN I2C1_Init 2 */

  /* USER CODE END I2C1_Init 2 */

}

/**
  * @brief SPI1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_SPI1_Init(void)
{

  /* USER CODE BEGIN SPI1_Init 0 */

  /* USER CODE END SPI1_Init 0 */

  /* USER CODE BEGIN SPI1_Init 1 */

  /* USER CODE END SPI1_Init 1 */
  /* SPI1 parameter configuration*/
  hspi1.Instance = SPI1;
  hspi1.Init.Mode = SPI_MODE_MASTER;
  hspi1.Init.Direction = SPI_DIRECTION_2LINES;
  hspi1.Init.DataSize = SPI_DATASIZE_8BIT;
  hspi1.Init.CLKPolarity = SPI_POLARITY_LOW;
  hspi1.Init.CLKPhase = SPI_PHASE_1EDGE;
  hspi1.Init.NSS = SPI_NSS_SOFT;
  hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_16;
  hspi1.Init.FirstBit = SPI_FIRSTBIT_MSB;
  hspi1.Init.TIMode = SPI_TIMODE_DISABLE;
  hspi1.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;
  hspi1.Init.CRCPolynomial = 10;
  if (HAL_SPI_Init(&hspi1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN SPI1_Init 2 */

  /* USER CODE END SPI1_Init 2 */

}

/**
  * @brief USART1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_USART1_UART_Init(void)
{

  /* USER CODE BEGIN USART1_Init 0 */

  /* USER CODE END USART1_Init 0 */

  /* USER CODE BEGIN USART1_Init 1 */

  /* USER CODE END USART1_Init 1 */
  huart1.Instance = USART1;
  huart1.Init.BaudRate = 115200;
  huart1.Init.WordLength = UART_WORDLENGTH_8B;
  huart1.Init.StopBits = UART_STOPBITS_1;
  huart1.Init.Parity = UART_PARITY_NONE;
  huart1.Init.Mode = UART_MODE_TX_RX;
  huart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart1.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN USART1_Init 2 */

  /* USER CODE END USART1_Init 2 */

}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* USER CODE BEGIN MX_GPIO_Init_1 */

  /* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOD_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET);

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0|GPIO_PIN_1, GPIO_PIN_RESET);

  /*Configure GPIO pin : PC13 */
  GPIO_InitStruct.Pin = GPIO_PIN_13;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);

  /*Configure GPIO pins : PA0 PA1 */
  GPIO_InitStruct.Pin = GPIO_PIN_0|GPIO_PIN_1;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

  /* USER CODE BEGIN MX_GPIO_Init_2 */

  /* USER CODE END MX_GPIO_Init_2 */
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
